/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          base: '#050505',
          surface: '#0a0a0a',
          elevated: '#111111',
          overlay: '#161616',
          border: '#242424',
          subtle: '#1b1b1b',
        },
        text: {
          primary: '#f5f5f5',
          secondary: '#b8b8b8',
          muted: '#6a6a6a',
          inverse: '#050505',
        },
        semantic: {
          up: '#00c978',
          down: '#ff4d6d',
          warning: '#c89b2c',
          info: '#ff7a1a',
          purple: '#9c6bff',
        },
        accent: {
          info: '#ff7a1a',
          green: '#00c978',
          red: '#ff4d6d',
          warning: '#c89b2c',
          purple: '#9c6bff',
        },
        interactive: {
          hover: '#131313',
          selected: '#1a1108',
          focus: '#ff7a1a',
          active: '#221407',
        },
        border: {
          DEFAULT: '#242424',
        },
      },
      fontFamily: {
        mono: ['"JetBrains Mono"', 'monospace'],
        sans: ['"JetBrains Mono"', 'monospace'],
        heading: ['"JetBrains Mono"', 'monospace'],
        ui: ['"JetBrains Mono"', 'monospace'],
        data: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1.2' }],
        sm: ['0.75rem', { lineHeight: '1.2' }],
        base: ['0.875rem', { lineHeight: '1.4' }],
        md: ['0.875rem', { lineHeight: '1.4' }],
        lg: ['1rem', { lineHeight: '1.2' }],
        xl: ['1.25rem', { lineHeight: '1.2' }],
        '2xl': ['1.5rem', { lineHeight: '1.2' }],
        '3xl': ['2rem', { lineHeight: '1.2' }],
        '4xl': ['2.5rem', { lineHeight: '1.1' }],
      },
      borderRadius: {
        none: '0',
        sm: '0',
        DEFAULT: '0',
        md: '0',
        lg: '0',
        xl: '0',
        full: '9999px',
      },
      spacing: {
        '0.5': '0.125rem',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
      },
      height: {
        'row-compact': '2rem',
        'row-default': '2.25rem',
        'row-relaxed': '2.5rem',
        'row-header': '2rem',
        'toolbar': '2.25rem',
        'topbar': '2.5rem',
        'filter': '2.25rem',
      },
    },
  },
  plugins: [],
}
