import { WidgetConfig } from './types';

export const WIDGET_REGISTRY: Record<string, WidgetConfig> = {
  // MARKET DATA
  watchlist: {
    id: 'watchlist',
    displayName: 'Watchlist',
    icon: 'List',
    shortcut: 'Alt+W',
    singleton: false,
    category: 'Market Data',
  },
  trending: {
    id: 'trending',
    displayName: 'Trending',
    icon: 'Globe',
    shortcut: '',
    singleton: true,
    category: 'Market Data',
  },
  indices: {
    id: 'indices',
    displayName: 'Indices',
    icon: 'Activity',
    shortcut: '',
    singleton: true,
    category: 'Market Data',
  },
  etf: {
    id: 'etf',
    displayName: 'ETF Scanner',
    icon: 'Search',
    shortcut: '',
    singleton: true,
    category: 'Market Data',
  },
  heatmap: {
    id: 'heatmap',
    displayName: 'Holdings Heatmap',
    icon: 'Grid',
    shortcut: '',
    singleton: true,
    category: 'Market Data',
  },

  // CHARTS & ANALYTICS
  chart: {
    id: 'chart',
    displayName: 'Chart',
    icon: 'LineChart',
    shortcut: 'F8',
    singleton: false,
    category: 'Charts & Analytics',
  },
  'oi-graph': {
    id: 'oi-graph',
    displayName: 'OI Graph',
    icon: 'BarChart2',
    shortcut: 'Alt+G',
    singleton: false,
    category: 'Charts & Analytics',
  },
  'iv-chart': {
    id: 'iv-chart',
    displayName: 'IV Chart',
    icon: 'TrendingUp',
    shortcut: '',
    singleton: false,
    category: 'Charts & Analytics',
  },
  'volatility-skew': {
    id: 'volatility-skew',
    displayName: 'Volatility Skew',
    icon: 'Waves',
    shortcut: '',
    singleton: false,
    category: 'Charts & Analytics',
  },
  'vol-surface-3d': {
    id: 'vol-surface-3d',
    displayName: 'Volatility Surface (3D)',
    icon: 'Mountain',
    shortcut: 'Alt+V',
    singleton: false,
    category: 'Charts & Analytics',
  },
  technicals: {
    id: 'technicals',
    displayName: 'Technicals',
    icon: 'Cpu',
    shortcut: 'Alt+T',
    singleton: false,
    category: 'Charts & Analytics',
  },
  vwap: {
    id: 'vwap',
    displayName: 'VWap Indicator',
    icon: 'Orbit',
    shortcut: '',
    singleton: false,
    category: 'Charts & Analytics',
  },

  // OPTIONS
  'options-chain': {
    id: 'options-chain',
    displayName: 'Options Chain',
    icon: 'Link',
    shortcut: 'Alt+O',
    singleton: false,
    category: 'Options',
  },
  'straddle-chain': {
    id: 'straddle-chain',
    displayName: 'Straddle Chain',
    icon: 'Split',
    shortcut: '',
    singleton: false,
    category: 'Options',
  },
  'futures-chain': {
    id: 'futures-chain',
    displayName: 'Futures Chain',
    icon: 'FastForward',
    shortcut: '',
    singleton: false,
    category: 'Options',
  },

  // ACCOUNT
  portfolio: {
    id: 'portfolio',
    displayName: 'Portfolio',
    icon: 'PieChart',
    shortcut: 'F12',
    singleton: true,
    category: 'Account',
  },
  positions: {
    id: 'positions',
    displayName: 'Positions',
    icon: 'Shield',
    shortcut: 'F4',
    singleton: true,
    category: 'Account',
  },
  orders: {
    id: 'orders',
    displayName: 'Orders',
    icon: 'Package',
    shortcut: 'F3',
    singleton: true,
    category: 'Account',
  },
  notifications: {
    id: 'notifications',
    displayName: 'Notifications',
    icon: 'Bell',
    shortcut: 'F9',
    singleton: true,
    category: 'Account',
  },
  basket: {
    id: 'basket',
    displayName: 'Basket',
    icon: 'ShoppingBasket',
    shortcut: '',
    singleton: false,
    category: 'Account',
  },


  // TOOLS
  news: {
    id: 'news',
    displayName: 'News',
    icon: 'Newspaper',
    shortcut: '',
    singleton: true,
    category: 'Tools',
  },
  'corp-actions': {
    id: 'corp-actions',
    displayName: 'Corporate Actions',
    icon: 'Briefcase',
    shortcut: '',
    singleton: true,
    category: 'Tools',
  },
  fundamentals: {
    id: 'fundamentals',
    displayName: 'Fundamentals',
    icon: 'BookOpen',
    shortcut: '',
    singleton: false,
    category: 'Tools',
  },

  // GAMES
  snake: {
    id: 'snake',
    displayName: 'Snake',
    icon: 'Gamepad2',
    shortcut: '',
    singleton: false,
    category: 'Take a Break',
  },
  minesweeper: {
    id: 'minesweeper',
    displayName: 'Minesweeper',
    icon: 'Bomb',
    shortcut: '',
    singleton: false,
    category: 'Take a Break',
  },
  wordle: {
    id: 'wordle',
    displayName: 'Wordle (Finance)',
    icon: 'Type',
    shortcut: '',
    singleton: false,
    category: 'Take a Break',
  },

  // INSTITUTIONAL INTEL (Ecosystem Pack 2)
  'fii-dii': {
    id: 'fii-dii',
    displayName: 'FII/DII Activity',
    icon: 'TrendingUp',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },
  'block-deals': {
    id: 'block-deals',
    displayName: 'Block Deals',
    icon: 'Zap',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },
  'fear-index': {
    id: 'fear-index',
    displayName: 'Fear & Greed Index',
    icon: 'Activity',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },
  'max-pain': {
    id: 'max-pain',
    displayName: 'Max Pain',
    icon: 'Target',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },
  'nl-screener': {
    id: 'nl-screener',
    displayName: 'Stock Screener',
    icon: 'Search',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },
  'filing-reader': {
    id: 'filing-reader',
    displayName: 'Exchange Filings',
    icon: 'FileText',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },
  'port-monitor': {
    id: 'port-monitor',
    displayName: 'Marine Map',
    icon: 'Anchor',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },
  'jet-tracker': {
    id: 'jet-tracker',
    displayName: 'Flight Map',
    icon: 'Plane',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },
  'accumulation-screener': {
    id: 'accumulation-screener',
    displayName: 'Accumulation Finder',
    icon: 'Filter',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
  },

  // NEW ACCOUNT WIDGETS
  holdings: {
    id: 'holdings',
    displayName: 'Holdings',
    icon: 'Briefcase',
    shortcut: 'Alt+H',
    singleton: true,
    category: 'Account',
  }
};

