import { WidgetConfig } from './types';
import { createWidgetPresentation } from './presentation';

export const WIDGET_REGISTRY: Record<string, WidgetConfig> = {
  watchlist: {
    id: 'watchlist',
    displayName: 'Watchlist',
    icon: 'List',
    shortcut: 'Alt+W',
    singleton: false,
    category: 'Market Data',
    presentation: createWidgetPresentation('table', {
      branding: { iconKey: 'List', tone: 'neutral' },
    }),
  },
  trending: {
    id: 'trending',
    displayName: 'Trending',
    icon: 'Globe',
    shortcut: '',
    singleton: true,
    category: 'Market Data',
    presentation: createWidgetPresentation('table', {
      branding: { iconKey: 'Globe', tone: 'accent' },
    }),
  },
  indices: {
    id: 'indices',
    displayName: 'Indices',
    icon: 'Activity',
    shortcut: '',
    singleton: true,
    category: 'Market Data',
    presentation: createWidgetPresentation('table', {
      branding: { iconKey: 'Activity', tone: 'accent' },
    }),
  },
  'etf-scanner': {
    id: 'etf-scanner',
    displayName: 'ETF Scanner',
    icon: 'Search',
    shortcut: '',
    singleton: true,
    category: 'Market Data',
    presentation: createWidgetPresentation('table', {
      branding: { iconKey: 'Search', tone: 'neutral' },
    }),
  },
  'holdings-heatmap': {
    id: 'holdings-heatmap',
    displayName: 'Holdings Heatmap',
    icon: 'Grid',
    shortcut: '',
    singleton: true,
    category: 'Market Data',
    presentation: createWidgetPresentation('canvas', {
      header: { mode: 'minimal', icon: 'show', logo: 'hide', subtitle: 'show', actions: 'minimal' },
      branding: { iconKey: 'Grid', tone: 'accent' },
      emptyState: 'canvas',
    }),
  },
  chart: {
    id: 'chart',
    displayName: 'Chart',
    icon: 'LineChart',
    shortcut: 'F8',
    singleton: false,
    category: 'Charts & Analytics',
    presentation: createWidgetPresentation('chart', {
      header: { mode: 'hidden' },
      branding: { iconKey: 'LineChart', tone: 'accent' },
    }),
  },
  'oi-graph': {
    id: 'oi-graph',
    displayName: 'OI Graph',
    icon: 'BarChart2',
    shortcut: 'Alt+G',
    singleton: false,
    category: 'Charts & Analytics',
    presentation: createWidgetPresentation('chart', {
      branding: { iconKey: 'BarChart2', tone: 'accent' },
    }),
  },
  'vol-surface-3d': {
    id: 'vol-surface-3d',
    displayName: 'Volatility Surface (3D)',
    icon: 'Mountain',
    shortcut: 'Alt+V',
    singleton: false,
    category: 'Charts & Analytics',
    presentation: createWidgetPresentation('canvas', {
      header: { mode: 'stacked', icon: 'show', logo: 'hide', subtitle: 'show', actions: 'minimal' },
      branding: { iconKey: 'Mountain', tone: 'accent' },
      emptyState: 'canvas',
    }),
  },
  technicals: {
    id: 'technicals',
    displayName: 'Technicals',
    icon: 'Cpu',
    shortcut: 'Alt+T',
    singleton: false,
    category: 'Charts & Analytics',
    presentation: createWidgetPresentation('table', {
      branding: { iconKey: 'Cpu', tone: 'neutral' },
    }),
  },
  'options-chain': {
    id: 'options-chain',
    displayName: 'Options Chain',
    icon: 'Link',
    shortcut: 'Alt+O',
    singleton: false,
    category: 'Options',
    presentation: createWidgetPresentation('table', {
      branding: { iconKey: 'Link', tone: 'accent' },
    }),
  },
  portfolio: {
    id: 'portfolio',
    displayName: 'Portfolio',
    icon: 'PieChart',
    shortcut: 'F12',
    singleton: true,
    category: 'Account',
    presentation: createWidgetPresentation('account', {
      branding: { iconKey: 'PieChart', tone: 'semantic' },
    }),
  },
  positions: {
    id: 'positions',
    displayName: 'Positions',
    icon: 'Shield',
    shortcut: 'F4',
    singleton: true,
    category: 'Account',
    presentation: createWidgetPresentation('account', {
      branding: { iconKey: 'Shield', tone: 'semantic' },
    }),
  },
  orders: {
    id: 'orders',
    displayName: 'Orders',
    icon: 'Package',
    shortcut: 'F3',
    singleton: true,
    category: 'Account',
    presentation: createWidgetPresentation('account', {
      branding: { iconKey: 'Package', tone: 'semantic' },
    }),
  },
  fundamentals: {
    id: 'fundamentals',
    displayName: 'Fundamentals',
    icon: 'BookOpen',
    shortcut: '',
    singleton: false,
    category: 'Tools',
    presentation: createWidgetPresentation('table', {
      branding: { iconKey: 'BookOpen', tone: 'neutral' },
    }),
  },
  'economic-calendar': {
    id: 'economic-calendar',
    displayName: 'Economic Calendar',
    icon: 'Calendar',
    shortcut: '',
    singleton: true,
    category: 'Tools',
    presentation: createWidgetPresentation('feed', {
      branding: { iconKey: 'Calendar', tone: 'accent' },
    }),
  },
  'world-bank-explorer': {
    id: 'world-bank-explorer',
    displayName: 'World Bank Macro',
    icon: 'Globe',
    shortcut: '',
    singleton: true,
    category: 'Tools',
    presentation: createWidgetPresentation('utility', {
      header: { mode: 'stacked', icon: 'show', logo: 'hide', subtitle: 'show', actions: 'minimal' },
      branding: { iconKey: 'Globe', tone: 'accent' },
    }),
  },
  snake: {
    id: 'snake',
    displayName: 'Snake',
    icon: 'Gamepad2',
    shortcut: '',
    singleton: false,
    category: 'Take a Break',
    presentation: createWidgetPresentation('marketing', {
      density: 'compact',
      header: { mode: 'minimal', icon: 'hide', logo: 'hide', subtitle: 'hide', actions: 'none' },
      branding: { iconKey: 'Gamepad2', tone: 'neutral' },
      emptyState: 'minimal',
    }),
  },
  minesweeper: {
    id: 'minesweeper',
    displayName: 'Minesweeper',
    icon: 'Bomb',
    shortcut: '',
    singleton: false,
    category: 'Take a Break',
    presentation: createWidgetPresentation('marketing', {
      density: 'compact',
      header: { mode: 'minimal', icon: 'hide', logo: 'hide', subtitle: 'hide', actions: 'none' },
      branding: { iconKey: 'Bomb', tone: 'neutral' },
      emptyState: 'minimal',
    }),
  },
  wordle: {
    id: 'wordle',
    displayName: 'Wordle (Finance)',
    icon: 'Type',
    shortcut: '',
    singleton: false,
    category: 'Take a Break',
    presentation: createWidgetPresentation('marketing', {
      density: 'compact',
      header: { mode: 'minimal', icon: 'hide', logo: 'hide', subtitle: 'hide', actions: 'none' },
      branding: { iconKey: 'Type', tone: 'neutral' },
      emptyState: 'minimal',
    }),
  },
  'shipping-traffic': {
    id: 'shipping-traffic',
    displayName: 'Shipping Traffic',
    icon: 'Anchor',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
    presentation: createWidgetPresentation('canvas', {
      header: { mode: 'stacked', icon: 'show', logo: 'hide', subtitle: 'show', actions: 'minimal' },
      branding: { iconKey: 'Anchor', tone: 'accent' },
      emptyState: 'canvas',
    }),
  },
  'air-traffic': {
    id: 'air-traffic',
    displayName: 'Air Traffic',
    icon: 'Radar',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
    presentation: createWidgetPresentation('canvas', {
      header: { mode: 'stacked', icon: 'show', logo: 'hide', subtitle: 'show', actions: 'minimal' },
      branding: { iconKey: 'Radar', tone: 'accent' },
      emptyState: 'canvas',
    }),
  },
  'fire-map': {
    id: 'fire-map',
    displayName: 'Thermal Fire Map',
    icon: 'Flame',
    shortcut: '',
    singleton: true,
    category: 'Institutional Intel',
    presentation: createWidgetPresentation('canvas', {
      header: { mode: 'stacked', icon: 'show', logo: 'hide', subtitle: 'show', actions: 'minimal' },
      branding: { iconKey: 'Flame', tone: 'accent' },
      emptyState: 'canvas',
    }),
  },
  holdings: {
    id: 'holdings',
    displayName: 'Holdings',
    icon: 'Briefcase',
    shortcut: 'Alt+H',
    singleton: true,
    category: 'Account',
    presentation: createWidgetPresentation('account', {
      branding: { iconKey: 'Briefcase', tone: 'semantic' },
    }),
  },
};
